### ISSUE TITLE
How to uninstall?

### ISSUE THREAD

**Issue by AccountOneOff** [thomasfinstad/tipsntricks#1]
I see this in the script but it's not working. 

```
sudo apt-get remove \$(apt list -i | grep $nvenc_postfix | cut -d/ -f1)"
bash: syntax error near unexpected token `('

sudo apt-get remove "$(apt list -i | grep $nvenc_postfix | cut -d/ -f1)"
Usage: grep [OPTION]... PATTERN [FILE]...
Try 'grep --help' for more information.

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

**Comment by thomasfinstad** [comment]
If you did not modify the script postfix it should be "NvencPenetalAutoScript", try this:
`sudo apt-get remove "$(apt list -i | grep "NvencPenetalAutoScript" | cut -d/ -f1)"`
And if you do not want to force a remove unless there is a new version:
`sudo apt-mark unhold "$(apt list -i | grep "NvencPenetalAutoScript" | cut -d/ -f1)"`

**Comment by thomasfinstad** [comment]
Sorry, I didnt test before posting. Fixed it below (and in repo README), also unless you want to remove everything for sure I recommend using the mark unhold and autoremove way:

> If you did not modify the script postfix it should be "NvencPenetalAutoScript", try this:
> 
> `sudo apt-get remove $(apt list -i | grep "NvencPenetalAutoScript" | cut -d/ -f1)`
> 
> And if you do not want to force a remove unless there is a new version or the packages are not needed:
> 
> `sudo apt-mark unhold $(apt list -i | grep "NvencPenetalAutoScript" | cut -d/ -f1) && sudo apt-get autoremove`
